-- --------------------------------------------------------
-- Anfitrião:                    127.0.0.1
-- Versão do servidor:           8.4.3 - MySQL Community Server - GPL
-- SO do servidor:               Win64
-- HeidiSQL Versão:              12.8.0.6908
-- --------------------------------------------------------

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET NAMES utf8 */;
/*!50503 SET NAMES utf8mb4 */;
/*!40103 SET @OLD_TIME_ZONE=@@TIME_ZONE */;
/*!40103 SET TIME_ZONE='+00:00' */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;

-- A despejar dados para tabela projeto.eventos: ~21 rows (aproximadamente)
INSERT INTO `eventos` (`id_evento`, `titulo`, `descricao`, `data`, `hora`, `local`, `participacao`, `img`, `regras`, `created_at`) VALUES
	('7wonders', 'Torneio de 7 Wonders', 'Compete na construção da tua civilização e conquista a glória no Torneio de 7 Wonders.', '2026-01-25', '16h30', 'Sede do Clube Ponto de Encontro - Rua dos Dados, nº 42, Coimbra', 'Máx. 7 participantes', 'imgs/torneio7wonders.jpg', '- Jogo base de 7 Wonders.\r\n- Mesas de 3 a 7 jogadores.\r\n- Partidas de 30-45 minutos cada.\r\n- Vitória pelo maior número de pontos acumulados.\r\n- Os 3 melhores jogadores avançam para a final.\r\n- Desempate baseado no maior número de cartas militares ou tesouros.', '2025-12-16 20:26:42'),
	('azul', 'Sessão Livre de Azul', 'Vem criar a mais bela parede de azulejos portugueses! Azul é um jogo estratégico, relaxante e visualmente apelativo.', '2026-01-15', '19h00', 'Sede do Clube Ponto de Encontro - Rua dos Dados, nº 42, Coimbra', 'Máx. 4 participantes', 'imgs/torneioazul.webp', '- Jogo base de Azul.\r\n- Mesas de 2 a 4 jogadores.\r\n- Partidas rápidas, duração média de 20-30 minutos.\r\n- Cada jogada tem limite de 45 segundos.\r\n- Não há eliminatórias — joga-se livremente.\r\n- Em caso de pontuação igual, vence quem tiver mais padrões completos.', '2025-12-16 20:26:42'),
	('azul2', 'Torneio de Azul (2ª Edição)', 'Segunda edição do Torneio de Azul, desafia a tua criatividade e habilidade na criação de padrões de azulejos.', '2026-02-12', '19h00', 'Sede do Clube Ponto de Encontro - Rua dos Dados, nº 42, Coimbra', 'Máx. 4 participantes', 'imgs/torneioazul.webp', '- Jogo base de Azul.\r\n- Mesas de 2 a 4 jogadores.\r\n- Partidas rápidas, duração média de 20-30 minutos.\r\n- Cada jogada tem limite de 45 segundos.\r\n- Não há eliminatórias — joga-se livremente.\r\n- Em caso de pontuação igual, vence quem tiver mais padrões completos.', '2025-12-16 20:26:42'),
	('batalha-naval', 'Mini Torneio de Batalha Naval', 'O Mini Torneio de Batalha Naval é um evento rápido e divertido, onde os jogadores demonstram estratégia, memória e capacidade de antecipar jogadas.', '2026-01-07', '19h00', 'Sede do Clube Ponto de Encontro - Rua dos Dados, nº 42, Coimbra', 'Máx. 12 participantes', 'imgs/torneiobatalhanaval.webp', '- Formato rápido “Melhor de 1”.\r\n- Tabuleiro clássico 10x10.\r\n- Tempo máximo por jogada: 20 segundos.\r\n- Sem recomeços — colocações iniciais são finais.\r\n- Os 4 melhores avançam para semifinal.\r\n- Final disputada entre os 2 vencedores.', '2025-12-16 20:26:42'),
	('carcassonne', 'Torneio de Carcassonne', 'Compete pela construção de cidades, estradas e mosteiros! O Torneio de Carcassonne põe à prova a tua estratégia e capacidade de adaptação.', '2026-01-17', '17h30', 'Sede do Clube Ponto de Encontro - Rua dos Dados, nº 42, Coimbra', 'Máx. 10 participantes', 'imgs/torneiocarcassonne.jpg', '- Jogo base de Carcassonne (sem expansões).\r\n- Partidas com 2 a 4 jogadores.\r\n- Tempo limite por partida: 35 minutos.\r\n- Vence quem tiver maior pontuação total no final.\r\n- Os 4 melhores jogadores avançam para a final.\r\n- Em caso de empate, decide-se pelo jogador com mais cidades completas.', '2025-12-16 20:26:42'),
	('carcassonne2', 'Torneio de Carcassonne (2ª Edição)', 'Segunda edição do Torneio de Carcassonne, colocando à prova a tua estratégia na construção de cidades.', '2026-02-07', '17h30', 'Sede do Clube Ponto de Encontro - Rua dos Dados, nº 42, Coimbra', 'Máx. 10 participantes', 'imgs/torneiocarcassonne.jpg', '- Jogo base de Carcassonne (sem expansões).\r\n- Partidas com 2 a 4 jogadores.\r\n- Tempo limite por partida: 35 minutos.\r\n- Vence quem tiver maior pontuação total no final.\r\n- Os 4 melhores jogadores avançam para a final.\r\n- Em caso de empate, decide-se pelo jogador com mais cidades completas.', '2025-12-16 20:26:42'),
	('catan', 'Torneio de Catan', 'O Torneio de Catan é um evento competitivo onde os jogadores demonstram estratégia, negociação e capacidade de adaptação.', '2025-12-20', '18h30', 'Sede do Clube Ponto de Encontro - Rua dos Dados, nº 42, Coimbra', 'Máx. 16 participantes', 'imgs/torneiocatan.png', '- Jogo base de Catan.\r\n- Partidas com 4 jogadores por mesa.\r\n- Vitória ao atingir 10 pontos.\r\n- Terás 60 segundos por jogada.\r\n- Os 4 vencedores avançam para a final.\r\n- Desempate por maior número de estradas.', '2025-12-16 20:26:42'),
	('catan2', 'Torneio de Catan (2ª Edição)', 'O Torneio de Catan é um evento competitivo onde os jogadores demonstram estratégia, negociação e capacidade de adaptação.', '2026-01-18', '16h30', 'Sede do Clube Ponto de Encontro - Rua dos Dados, nº 42, Coimbra', 'Máx. 16 participantes', 'imgs/torneiocatan.png', '- Jogo base de Catan.\r\n- Partidas com 4 jogadores por mesa.\r\n- Vitória ao atingir 10 pontos.\r\n- Terás 60 segundos por jogada.\r\n- Os 4 vencedores avançam para a final.\r\n- Desempate por maior número de estradas.', '2025-12-16 20:26:42'),
	('cluedo', 'Sessão Livre de Cluedo', 'Junta-te a nós para uma tarde de investigação onde cada detalhe conta. Na Sessão Livre de Cluedo poderás resolver mistérios e trabalhar em equipa.', '2026-01-09', '21h30', 'Sede do Clube Ponto de Encontro - Rua dos Dados, nº 42, Coimbra', 'Máx. 6 participantes', 'imgs/torneiocluedo.jpg', '- Jogo base de Cluedo.\r\n- Partidas livres, sem limite de rondas.\r\n- Máximo 6 jogadores por mesa.\r\n- Cada jogador tem 30 segundos por jogada.\r\n- Não há eliminatórias — podes jogar várias partidas seguidas.\r\n- Em caso de empate numa acusação, vence quem apresentou a dedução mais completa.', '2025-12-16 20:26:42'),
	('damas', 'Sessão Livre de Damas', 'A sessão livre de Damas é uma atividade descontraída onde qualquer pessoa pode participar, aprender e jogar de forma informal.', '2025-12-30', '17h30', 'Sede do Clube Ponto de Encontro - Rua dos Dados, nº 42, Coimbra', 'Máx. 20 participantes', 'imgs/torneiodamas.jpg', '- Atividade livre, sem formato competitivo.\r\n- Rotação de mesas a cada 15 minutos.\r\n- É permitido jogar mais do que uma partida.\r\n- Respeito e espírito de convivência.', '2025-12-16 20:26:42'),
	('damas2', 'Mini Torneio de Damas', 'O Mini Torneio de Damas é uma atividade aberta a todos, onde qualquer pessoa pode participar, aprender e jogar num ambiente descontraído.', '2026-01-21', '19h30', 'Sede do Clube Ponto de Encontro - Rua dos Dados, nº 42, Coimbra', 'Máx. 20 participantes', 'imgs/torneiodamas.jpg', '- Formato rápido “Melhor de 1”.\r\n- Tabuleiro clássico 8x8.\r\n- Tempo máximo por jogada: 30 segundos.\r\n- Capturas obrigatórias segundo as regras tradicionais.\r\n- Não há empates — em caso de bloqueio vence quem tiver mais peças.\r\n- Os 4 melhores avançam para semifinais.\r\n- A final é disputada entre os vencedores das semifinais.', '2025-12-16 20:26:42'),
	('dixit', 'Sessão Livre de Dixit', 'Junta-te a nós para uma sessão criativa de Dixit, onde imaginação e interpretação são essenciais.', '2026-01-23', '18h30', 'Sede do Clube Ponto de Encontro - Rua dos Dados, nº 42, Coimbra', 'Máx. 6 participantes', 'imgs/torneiodixit.webp', '- Jogo base de Dixit.\r\n- Mesas de 3 a 6 jogadores.\r\n- Cada rodada permite aos jogadores contar uma história ou frase sobre a carta escolhida.\r\n- Pontuação baseada na adivinhação correta das cartas dos outros.\r\n- Sem eliminatórias — joga-se livremente várias rodadas.\r\n- Em caso de empate, vence quem tiver mais cartas interpretadas corretamente.', '2025-12-16 20:26:42'),
	('domino', 'Torneio de Dominó', 'O Torneio de Dominó é uma competição amigável onde estratégia, gestão de peças e antecipação são essenciais.', '2026-01-03', '21h30', 'Sede do Clube Ponto de Encontro - Rua dos Dados, nº 42, Coimbra.', '32 participantes', 'imgs/torneiodomino.webp', '- Jogos a 2 jogadores por mesa.\r\n- Formato eliminatório.\r\n- Vitória em 2 partidas (melhor de 3).\r\n- Tempo máximo por partida: 20 minutos.\r\n- Final disputada à melhor de 5 partidas.\r\n- Critério de desempate: menor número de peças restantes.', '2025-12-16 20:26:42'),
	('encontros-semanais', 'Encontros Semanais', 'Os Encontros Semanais são momentos de convívio abertos a todos os amantes de jogos de tabuleiro.', '2026-01-04', '14h30', 'Sede do Clube Ponto de Encontro - Rua dos Dados, nº 42, Coimbra', 'Livre e Gratuita', 'imgs/encontros-semanais.jpg', '- Chega quando quiseres e joga o que te apetecer.\r\n- Há mesas disponíveis para jogos estratégicos, familiares e rápidos.\r\n- Voluntários ajudam a explicar regras sempre que necessário.\r\n- Podes trazer jogos ou usar os do clube.\r\n- Ambiente informal e perfeito para conhecer novos jogadores.', '2025-12-16 20:26:42'),
	('monopoly', 'Torneio de Monopoly', 'No Torneio de Monopoly, os jogadores competem pelo domínio financeiro. Compra propriedades, negocia e evita a falência.', '2026-01-11', '17h00', 'Sede do Clube Ponto de Encontro - Rua dos Dados, nº 42, Coimbra.', '8 participantes', 'imgs/torneiomonopoly.jpg', '- Jogo base de Monopoly (versão clássica).\r\n- Partidas com 4 jogadores por mesa.\r\n- Tempo limite: 60 minutos por partida.\r\n- Vence quem tiver maior património total no final do tempo.\r\n- Os 4 vencedores com maior património avançam para a final.\r\n- Em caso de empate, decide-se pelo jogador com mais propriedades.', '2025-12-16 20:26:42'),
	('pandemic', 'Sessão Livre de Pandemic', 'Trabalha em equipa para salvar o mundo! Na Sessão Livre de Pandemic, tu e o teu grupo irão combater surtos e evitar pandemias.', '2026-01-13', '18h30', 'Sede do Clube Ponto de Encontro - Rua dos Dados, nº 42, Coimbra.', '4 participantes', 'imgs/torneiopandemic.jpg', '- Jogo base de Pandemic (nível: Standard).\r\n- Sessões cooperativas com 2 a 4 jogadores.\r\n- Cada equipa pode repetir partidas quantas vezes desejar.\r\n- Tempo máximo por partida: 45 minutos.\r\n- Incentiva-se a rotação de papéis entre jogos.\r\n- Se o grupo vencer, pode tentar um nível superior opcional.', '2025-12-16 20:26:42'),
	('risk', 'Torneio de Risk', 'Desafia os teus amigos e conquista o mundo no Torneio de Risk, um clássico dos jogos de estratégia.', '2026-01-30', '17h30', 'Sede do Clube Ponto de Encontro - Rua dos Dados, nº 42, Coimbra', 'Máx. 6 participantes', 'imgs/torneiorisk.webp', '- Jogo base de Risk (sem expansões).\r\n- Mesas de 2 a 6 jogadores.\r\n- Partidas com limite de tempo: 90 minutos.\r\n- Objetivo: conquistar territórios e eliminar adversários.\r\n- Os 2 melhores avançam para a final.\r\n- Em caso de empate, vence quem tiver maior número de territórios controlados.', '2025-12-16 20:26:42'),
	('scrabble', 'Torneio de Scrabble', 'Testa o teu vocabulário e habilidade estratégica no Torneio de Scrabble.', '2026-02-03', '18h30', 'Sede do Clube Ponto de Encontro - Rua dos Dados, nº 42, Coimbra', 'Máx. 4 participantes', 'imgs/torneioscrabble.webp', '- Jogo base de Scrabble (versão portuguesa).\r\n- Mesas de 2 a 4 jogadores.\r\n- Partidas com limite de tempo: 60 minutos.\r\n- Pontuação baseada nas palavras criadas.\r\n- Os 2 melhores jogadores avançam para a final.\r\n- Em caso de empate, vence quem tiver usado palavras com maior pontuação total.', '2025-12-16 20:26:42'),
	('ticket-to-ride', 'Sessão Livre de Ticket to Ride', 'Constrói rotas de trem e liga cidades no Ticket to Ride, um jogo divertido e estratégico para todos.', '2026-02-01', '16h00', 'Sede do Clube Ponto de Encontro - Rua dos Dados, nº 42, Coimbra', 'Máx. 5 participantes', 'imgs/torneioticket.jpg', '- Jogo base de Ticket to Ride.\r\n- Mesas de 2 a 5 jogadores.\r\n- Duração média: 45-60 minutos por partida.\r\n- Objetivo: completar rotas e acumular pontos.\r\n- Sem eliminatórias — partidas livres.\r\n- Em caso de empate, vence quem tiver completado mais rotas.', '2025-12-16 20:26:42'),
	('xadrez', 'Torneio de Xadrez', 'O Torneio de Xadrez é pensado para jogadores de todos os níveis. O objetivo é proporcionar jogos equilibrados e emocionantes.', '2025-12-27', '21h30', 'Sede do Clube Ponto de Encontro - Rua dos Dados, nº 42, Coimbra.', '20 participantes', 'imgs/torneioxadrez.jpg', '- Sistema suíço em 5 rondas.\r\n- Relógio de 10 minutos por jogador.\r\n- Empates contam como 0.5 pontos.\r\n- Vitória conta como 1 ponto.\r\n- Derrota conta como 0 pontos.\r\n- Desempate: confronto direto → Buchholz → maior número de vitórias.', '2025-12-16 20:26:42'),
	('xadrez2', 'Torneio de Xadrez (2ª Edição)', 'Segunda edição do Torneio de Xadrez, promovendo jogos equilibrados e estratégia para todos os níveis.', '2026-02-04', '19h00', 'Sede do Clube Ponto de Encontro - Rua dos Dados, nº 42, Coimbra.', '20 participantes', 'imgs/torneioxadrez.jpg', '- Sistema suíço em 5 rondas.\r\n- Relógio de 10 minutos por jogador.\r\n- Empates contam como 0.5 pontos.\r\n- Vitória conta como 1 ponto.\r\n- Derrota conta como 0 pontos.\r\n- Desempate: confronto direto → Buchholz → maior número de vitórias.', '2025-12-16 20:26:42');

/*!40103 SET TIME_ZONE=IFNULL(@OLD_TIME_ZONE, 'system') */;
/*!40101 SET SQL_MODE=IFNULL(@OLD_SQL_MODE, '') */;
/*!40014 SET FOREIGN_KEY_CHECKS=IFNULL(@OLD_FOREIGN_KEY_CHECKS, 1) */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40111 SET SQL_NOTES=IFNULL(@OLD_SQL_NOTES, 1) */;
